/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PuzzleGame;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author devam
 */

class node {
	String name;
	int score1;

	node(String name, int score1) {
		this.name = name;
		this.score1 = score1;
	}
}
class sort1 implements Comparator<node> {
        @Override
	public int compare(node a, node b) {
		if (a.score1 > b.score1)
			return 1;
		else if (a.score1 == b.score1) {
			return a.name.compareTo(b.name);
		}
		return -1;
	}
}
public class LeaderBoard extends javax.swing.JFrame {
    ArrayList<node> board = new ArrayList<node>();
    String getCd = System.getProperty("user.dir");
    String path_1;
    String[] columns = { "Player Name", "Score(moves)" };
    DefaultTableModel tableModel = new DefaultTableModel(columns, 0);
    /**
     * Creates new form LeaderBoard
     */
    public LeaderBoard() {
        initComponents();
        int flag1 = 0;
		for (int i = 0; i < getCd.length() - 1; i++) {
			if (getCd.substring(i, i + 1).equals("/")) {
				flag1 = 1;
				break;
			}
		}
		if (flag1 == 0) {
			getCd += "\\database.txt";
		} else {
			getCd += "/database.txt";
		}
		path_1 = getCd;
		System.out.println(path_1);
        
		File ff1 = new File(path_1);
		board.clear();
		try {
			Scanner sc1 = new Scanner(ff1);
			while (true) {
				String temp = sc1.nextLine();
                                System.out.println(temp + "less");
				if (temp.length() == 0 || temp.charAt(0) == '\n') {
					System.out.println("ArrayList Ended\n");
					break;
				}
				String[] t1 = temp.split(" ");
				System.out.println(temp);
				node obj = new node(t1[1], Integer.parseInt(t1[0]));
				board.add(obj);
			}
			// System.out.println("MMMMM\n");
		} catch (Exception E) {
			System.out.println("Exception!!!!"+ E);
		}
		String[][] data = new String[100][100];
		if (board == null) {

		} else {
			Collections.sort(board, new sort1());
			// for(int i1=0;i1<leaderboard.size();i1++)
			// {
			// System.out.println("--->>>"+leaderboard.get(i1));
			// }
			
			for (int i1 = 0; i1 < board.size(); i1++) {
				// String[] total=leaderboard.get(i1).split(" ");
				int scoree = board.get(i1).score1;
				String name2 = board.get(i1).name;
				// data.add({name2,scoree});
                                Object[] objs = {name2,scoree};
				tableModel.addRow(objs);
                                
			}
                       tableModel.fireTableDataChanged();
		}

		// Column Names
		

		// Initializing the JTable
		
		

		// adding it to JScrollPane
		
		
		// Frame Size
		
		// Frame Visible = true
		

	
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        leaderboard = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leaderboard.setModel(tableModel);
        jScrollPane1.setViewportView(leaderboard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaderBoard().setVisible(true);
            }
        });
    }
    
                 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable leaderboard;
    // End of variables declaration//GEN-END:variables
}
